In [2]:
# Installation of NumPy
#If you have Python and PIP already installed on a system, then installation of NumPy is very easy.Install it using this command:
#C:\Users\Your Name>pip install numpy
#Import NumPy
#Once NumPy is installed, import it in your applications by adding the import keyword:
import numpy

In [3]:
#Example:
import numpy
arr = numpy.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [4]:
#Numpy as np:
#NumPy is usually imported under the np alias.
#Alias: In Python alias are an alternate name for referring to the same thing.
#Create an alias with the as keyword while importing:
import numpy as np
#Example:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [5]:
#Checking NumPy Version:
#The version string is stored unde" __version__ attribute."
#Example
import numpy as np
print(np.__version__)

2.0.1


In [2]:
#Create a NumPy ndarray Object:
#Numpy is used to work with arrays.The array object in NumPy is called ndarray.
#We can create a NumPy ndarray object by using the array() function.
#Example:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
#To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:
#Example
#Use a tuple to create a NumPy array:
import numpy as np
arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


In [4]:
#Dimensions in Arrays:A dimension in arrays is one level of array depth (nested arrays).
#Nested array: are arrays that have arrays as their elements.
#0-D Arrays:0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.
#Example
#Create a 0-D array with value 42
import numpy as np
arr = np.array(42)
print(arr)

42


In [5]:
#Example:Create a 1-D array containing the values 1,2,3,4,5:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [6]:
#Example:Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
#3-D arrays:An array that has 2-D arrays (matrices) as its elements is called 3-D array.These are often used to represent a 3rd order tensor.
#Example:Create a 3-D array with two 2-D arrays,both containing two arrays with the values 1,2,3 and 4,5,6:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [8]:
#Example:Check how many dimensions the arrays have:
import numpy as np
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [9]:
#Higher Dimensional Arrays:An array can have any number of dimensions.When the array is created, you can define the number of dimensions by using the ndmin argument.
#Example:Create an array with 5 dimensions and verify that it has 5 dimensions:
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [12]:
#Exercise:Insert the correct method for creating a NumPy array.
#arr = np.--------([1, 2, 3, 4, 5])
#Solution:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [13]:
#Access Array Elements:Array indexing is the same as accessing an array element.You can access an array element by referring to its index number.
#The indexes in NumPy arrays start with 0,meaning that the first element has index 0, and the second has index 1 etc.
#Example:Get the first element from the following array:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[0])

1


In [19]:
#Example:Get third and fourth elements from the following array and add them:
#1. Take power of the third element.
#2. Take the squareroot of second element.[4,5,6,7,8,9]:
#Solution: 
import numpy as np
arr = np.array([4, 5, 6, 7, 8, 9])
sum_third_fourth = arr[2] + arr[3]
print("Sum of third and fourth elements:", sum_third_fourth)
# Power of the third element
power_third = arr[2] ** 2
print("Power of the third element:", power_third)
# Square root of the second element
sqrt_second = np.sqrt(arr[1])
print("Square root of the second element:", sqrt_second)


Sum of third and fourth elements: 13
Power of the third element: 36
Square root of the second element: 2.23606797749979


In [33]:
#use of concatenate 
import numpy as nm
arr1 = nm.array([1, 2, 3])
arr2 = nm.array([4, 5, 6])
arr= nm.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [20]:
#Example:Access the element on the 2nd row, 5th column:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [22]:
#Slicing 2-D Arrays
#Example:From the second element, slice elements from index 1 to index 4 (not included):
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [23]:
#Checking the Data Type of an Array:The NumPy array object has a property called dtype that returns the data type of the array:
#Example:Get the data type of an array object:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


In [24]:
#Create an array with data type string:
import numpy as np
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [25]:
#for i, u, f, S and U we can define size as well.
#Example:Create an array with data type 4 bytes integer:
import numpy as np
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [27]:
#Example:A non integer string like 'a' cannot be converted to integer (will raise an error):
import numpy as np
try:
  arr = np.array(['a', '2', '3'], dtype='i')
except ValueError as e:
  print(f"Error: {e}")

Error: invalid literal for int() with base 10: 'a'


In [28]:
#Example:Change data type from float to integer by using 'i' as parameter value:
import numpy as np
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [29]:
#Example:Change data type from float to integer by using int as parameter value:
import numpy as np
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [30]:
#Shape of an Array:The shape of an array is the number of elements in each dimension.Get the Shape of an Array NumPy arrays have an attribute called shape that returns a tuple with each index having the number 
#of corresponding elemens.
#Example:Print the shape of a 2-D array:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [31]:
#Example:Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [1]:
#Reshaping arrays:Reshaping means changing the shape of an array.
#The shape of an array is the number of elements in each dimension.By reshaping we can add or remove dimensions or change number of elements in each dimension.
#Reshape From 1-D to 2-D
#Example:Convert the following 1-D array with 12 elements into a 2-D array.
#The outermost dimension will have 4 arrays, each with 3 elements:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [2]:
#Reshape From 1-D to 3-D
#Example:Convert the following 1-D array with 12 elements into a 3-D array.
#The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [3]:
#Returns Copy or View?
#Example:Check if the returned array is a copy or a view:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)
#The example above returns the original array, so it is a view.

[1 2 3 4 5 6 7 8]


In [4]:
#Iterating Arrays:Iterating means going through elements one by one.
#As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.
#If we iterate on a 1-D array it will go through each element one by one.
#Example:Iterate on the elements of the following 1-D array:
import numpy as np
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

1
2
3


In [5]:
#Iterating 2-D Arrays:In a 2-D array it will go through all the rows.
#Example:Iterate on the elements of the following 2-D array:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [6]:
#Example:Iterate on each scalar element of the 2-D array:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [7]:
#Example:Iterate down to the scalars:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [8]:
#Joining NumPy Arrays:Joining means putting contents of two or more arrays in a single array.
#In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.
#We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.
#Example:Join two arrays
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [9]:
#Example:Join two 2-D arrays along rows (axis=1):
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [10]:
#Splitting NumPy Arrays:Splitting is reverse operation of Joining.
#Joining merges multiple arrays into one and Splitting breaks one array into multiple.
#We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.
#Example:Split the array in 3 parts:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [11]:
#Example:Split the 2-D array into three 2-D arrays.
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [12]:
#Searching Arrays:You can search an array for acertain value, and return the indexes that get a match.
#To search an array, use the where() method.
#Example:Find the indexes where the value is 4:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


In [13]:
#Example:Find the indexes where the values are even:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7]),)


In [15]:
#Find the indexes where the values are odd.
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
y = np.where(arr % 2 != 0)
print(y)

(array([0, 2, 4, 6]),)


In [16]:
#Sorting Arrays:Sorting means putting elements in an ordered sequence.
#Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.
#The NumPy ndarray object has a function called sort(), that will sort a specified array.
#Example:Sort the array:
import numpy as np
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [18]:
#Sort the array alphabetically:['banana', 'cherry', 'apple']
import numpy as np
arr=np.array(['banana','Cherry','Apple'])
print(np.sort(arr))

['Apple' 'Cherry' 'banana']


In [19]:
#Sorting a 2-D Array:If you use the sort() method on a 2-D array, both arrays will be sorted:
#Example:Sort a 2-D array:
import numpy as np
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [20]:
#Filtering Arrays:Getting some elements out of an existing array and creating a new array out of them is called filtering.
#In NumPy, you filter an array using a boolean index list. A boolean index list is a list of booleans corresponding to indexes in the array.
#If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.
#Example:Create an array from the elements on index 0 and 2:
import numpy as np
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


In [21]:
#Example:
arr=np.array([1,2,3,4,5,6,7,8])
for x in arr:
 if x%2==0:
    print("True")
 else:
    print("False")
newarr=arr.copy()
print((newarr))

False
True
False
True
False
True
False
True
[1 2 3 4 5 6 7 8]
